name: dog-breed-classification

channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Core ML and Deep Learning
  - tensorflow=2.15.0
  - numpy=1.24.3
  - scipy=1.11.1

  # Data Processing
  - pandas=2.0.3
  - scikit-learn=1.3.0

  # Computer Vision
  - pillow=10.0.0
  - opencv=4.8.1

  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2

  # Jupyter
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - notebook=7.0.2

  # Utilities
  - tqdm=4.65.0

  # Pip packages (không có sẵn trên conda)
  - pip
  - pip:
    - keras==2.15.0
    - albumentations==1.3.1
    - plotly==5.15.0
    - tensorflow-datasets==4.9.2
    - pathlib2==2.3.7
    - flatbuffers==23.5.26
    - tensorflow-model-optimization==0.7.4
    - ipywidgets==8.1.0